version: "3.0"

services:
  api_service:
    build: backend/
    depends_on:
      - redis_db
    ports:
      - "8080:8080"

  redis_db:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "KEAx"]
